development: 
  encoding: unicode
  adapter: postgresql
  port: 5432                     
  host: localhost
  database: lembremeuscontatos
  username: postgres
  password: postgres

test: 
  encoding: unicode
  adapter: postgresql
  port: 5432     
  host: localhost
  database: lembremeuscontatos
  username: postgres
  password: postgres

production: 
  encoding: unicode
  adapter: postgresql
  port: 5432
  database: lembremeuscontatos
  username: lembremeuscontatos
  password: $lembremeuscontatos!$