development: 
  encoding: unicode
  adapter: postgresql
  port: 5432                     
  host: localhost
  username: postgres
  database: lembremeuscontatos
  password: $lembremeuscontatos!$

test: 
  encoding: unicode
  adapter: postgresql
  port: 5432     
  host: localhost
  username: postgres
  database: lembremeuscontatos
  password: $lembremeuscontatos!$

production: 
  encoding: unicode
  adapter: postgresql
  port: 5432
  username: postgres
  database: lembremeuscontatos
  password: $lembremeuscontatos!$