development:
  api_key: "hmHGkZGBQXadnYUhSTCVhg"
  access_token: "193907969-vKFVg2MC64eSy1zYubejoF8i1PVxkhsPscI4zwRv"
  access_secret: "qOSqHFBR0z4L3pmtGnSflrKVPKdybb1B6JoMWNINIE"
  consumer_key: "hmHGkZGBQXadnYUhSTCVhg"
  consumer_secret: "dJq2u4JFqR466HGNti3kGSwTBX3KzUf68rHjmVVNU"
  username: 'lmcontatos'